/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Clause: typeof import('./src/components/Clause.vue')['default']
    Close_icon: typeof import('./src/components/icon/close_icon.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon_test: typeof import('./src/components/icon_test.vue')['default']
    MainBtn: typeof import('./src/components/MainBtn.vue')['default']
    OptionStrip: typeof import('./src/components/OptionStrip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserBox: typeof import('./src/components/UserBox.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanOverlay: typeof import('vant/es')['Overlay']
  }
}
