/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicBtn: typeof import('./src/components/btns/BasicBtn.vue')['default']
    BlackBtn: typeof import('./src/components/btns/BlackBtn.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainBtn: typeof import('./src/components/MainBtn.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RedBtn: typeof import('./src/components/btns/RedBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanNavBar: typeof import('vant/es')['NavBar']
    WhiteBtn: typeof import('./src/components/btns/WhiteBtn.vue')['default']
  }
}
